### ISSUE TITLE
The minDeposit shouldn't be assigned by Solver when registering a task

### ISSUE THREAD

**Issue by iisaint** [TrueBitFoundation/truebit-contracts#10]
Hi there,
In my understanding, the minDeposit is fixed after creating a task. It should not be assigned again by Solver when registering a task. Otherwise, Solver can assign an arbitrary value to take the task.

https://github.com/TrueBitFoundation/truebit-contracts/blob/ddeaca94d7f6198392a5580c99017c65c2db420a/contracts/TaskBook.sol#L42-L43

Please refer to the following code for fix it.

```
function registerForTask(uint taskID, bytes32 randomBitsHash) returns(bool) {
    Task t = tasks[taskID];
    require(balances[msg.sender] >= t.minDeposit);
    ...
}
```

**Comment by hswick** [comment]
Ah, yes you are right. Thanks!
