### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by hswick** [TrueBitFoundation/truebit-contracts#12]
Specific timeouts for each state

Add require for block numbers

Need to partition timesteps

**Comment by SeanAvery** [comment]
@hswick timeouts in terms of blocks or timestamps?

Timestamps are arguably not secure as miners have freedom to add whatever timestamp they want to the header. 

Practically, clients will reject timestamp if less then previous block or too far ahead... but something to consider.

**Comment by hswick** [comment]
@SeanAvery I have timeouts in terms of block numbers, so sounds like I'll stick with that
