### ISSUE TITLE
Test timeout triggers

### ISSUE THREAD

**Issue by hswick** [TrueBitFoundation/truebit-contracts#18]
Need to come up with a method for testing these.

Little complex because the timeouts are inherently asynchronous and need to know the rate of blocks per second to specify timeouts on client end. Also need to know this rate for the testrpc.

Any advice or help would be appreciated.

**Comment by mrsmkl** [comment]
I think testrpc will generate a block for each transaction by default.

**Comment by SeanAvery** [comment]
@hswick 

You can specify a starting timestamp for the chain, something like -->
```
var TestRPC = require("ethereumjs-testrpc");
var server = TestRPC.server({"time": 10000});
server.listen(port, function(err, blockchain) {...});
```

then to traverse time, you can use testrpc specific `evm_increaseTime` rpc endpoint

**Comment by hswick** [comment]
@mrsmkl @SeanAvery thanks! I'll mess around with that when I get a chance.

**Comment by hswick** [comment]
Found this stackoverflow question to be useful. Noting this here https://ethereum.stackexchange.com/questions/21509/truffle-testrpc-time-manipulation
