### ISSUE TITLE
Do not assume that taskGiver needs to bond minDeposit as a reward. 

### ISSUE THREAD

**Issue by sinahab** [TrueBitFoundation/truebit-contracts#20]
Currently, the `createTask` function requires the taskGiver to submit minDeposit eth. This is not necessarily correct, as the taskGiver is submitting a reward, whereas minDeposit applies to solvers and verifiers. 

The reward and the minDeposit are two independent numbers:
* the reward is determined by the task difficulty.
* the minDeposit is set to prevent DoS and increase cost of attack given downstream economic dependencies.

We should separate these out.

**Comment by hswick** [comment]
Okay so createTask should take another argument? and reward should be another field in the Task struct?

**Comment by sinahab** [comment]
Yep, I think that's a good v1. Later we'll need to make the contract enforce a minimum required reward given the task's difficulty
