### ISSUE TITLE
Tasks specific numBlocks attribute not being used

### ISSUE THREAD

**Issue by hswick** [TrueBitFoundation/truebit-contracts#34]
Setting t.numBlocks with numBlocks on createTask in upcoming PR. However the value is never being used.

@sinahab thoughts?

**Comment by sinahab** [comment]
`numBlocks` could be referring the the challenge timeout (i.e. how long a solution needs to go unchallenged, before it’s deemed correct); or it could be referring to the timeout before the different stages of a task (i.e. waiting for solution to come in, for challenge to come in, etc)

I think it's cool if we delete it and/or add another variable as we fully implement the timeouts.

**Comment by hswick** [comment]
Using for timeout now
