### ISSUE TITLE
Setup Travis

### ISSUE THREAD

**Issue by hswick** [TrueBitFoundation/truebit-contracts#46]
Need a .travis.yml for CI

**Comment by bloodstalker** [comment]
shall I?

**Comment by sinahab** [comment]
@bloodstalker – for sure, that would be great!

**Comment by bloodstalker** [comment]
this how the travis build looks for my fork. im running `truffle test`. one of the truffle tests fail.
https://travis-ci.org/bloodstalker/truebit-contracts/builds/339763627
the `README.md` mentions two test files that are not there.
so i guess lemme know how you want to do the tests or if there re other things you need to setup as well.

**Comment by hswick** [comment]
Latest PR merge should fix that now

**Comment by bloodstalker** [comment]
Here's the PR. someone needs to enable travis for the repo though.

**Comment by hswick** [comment]
@zmitton was the creator. Waiting on response to get admin rights from him

**Comment by hswick** [comment]
@bloodstalker travis has been enabled. Can you send a push to your PR to trigger the build?
